// flow-typed signature: 5ac114339bab6ca1fa7f0a0339557fa0
// flow-typed version: <<STUB>>/electron-forge_v5.2.2/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'electron-forge'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'electron-forge' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'electron-forge/dist/api/import' {
  declare module.exports: any;
}

declare module 'electron-forge/dist/api/index' {
  declare module.exports: any;
}

declare module 'electron-forge/dist/api/init' {
  declare module.exports: any;
}

declare module 'electron-forge/dist/api/install' {
  declare module.exports: any;
}

declare module 'electron-forge/dist/api/lint' {
  declare module.exports: any;
}

declare module 'electron-forge/dist/api/make' {
  declare module.exports: any;
}

declare module 'electron-forge/dist/api/package' {
  declare module.exports: any;
}

declare module 'electron-forge/dist/api/publish' {
  declare module.exports: any;
}

declare module 'electron-forge/dist/api/start' {
  declare module.exports: any;
}

declare module 'electron-forge/dist/electron-forge-import' {
  declare module.exports: any;
}

declare module 'electron-forge/dist/electron-forge-init' {
  declare module.exports: any;
}

declare module 'electron-forge/dist/electron-forge-install' {
  declare module.exports: any;
}

declare module 'electron-forge/dist/electron-forge-lint' {
  declare module.exports: any;
}

declare module 'electron-forge/dist/electron-forge-make' {
  declare module.exports: any;
}

declare module 'electron-forge/dist/electron-forge-package' {
  declare module.exports: any;
}

declare module 'electron-forge/dist/electron-forge-publish' {
  declare module.exports: any;
}

declare module 'electron-forge/dist/electron-forge-start' {
  declare module.exports: any;
}

declare module 'electron-forge/dist/electron-forge' {
  declare module.exports: any;
}

declare module 'electron-forge/dist/forge-import' {
  declare module.exports: any;
}

declare module 'electron-forge/dist/forge-init' {
  declare module.exports: any;
}

declare module 'electron-forge/dist/forge-install' {
  declare module.exports: any;
}

declare module 'electron-forge/dist/forge-lint' {
  declare module.exports: any;
}

declare module 'electron-forge/dist/forge-make' {
  declare module.exports: any;
}

declare module 'electron-forge/dist/forge-package' {
  declare module.exports: any;
}

declare module 'electron-forge/dist/forge-publish' {
  declare module.exports: any;
}

declare module 'electron-forge/dist/forge-start' {
  declare module.exports: any;
}

declare module 'electron-forge/dist/forge' {
  declare module.exports: any;
}

declare module 'electron-forge/dist/init/init-custom' {
  declare module.exports: any;
}

declare module 'electron-forge/dist/init/init-directory' {
  declare module.exports: any;
}

declare module 'electron-forge/dist/init/init-git' {
  declare module.exports: any;
}

declare module 'electron-forge/dist/init/init-npm' {
  declare module.exports: any;
}

declare module 'electron-forge/dist/init/init-standard-fix' {
  declare module.exports: any;
}

declare module 'electron-forge/dist/init/init-starter-files' {
  declare module.exports: any;
}

declare module 'electron-forge/dist/installers/darwin/dmg' {
  declare module.exports: any;
}

declare module 'electron-forge/dist/installers/darwin/zip' {
  declare module.exports: any;
}

declare module 'electron-forge/dist/installers/linux/deb' {
  declare module.exports: any;
}

declare module 'electron-forge/dist/installers/linux/rpm' {
  declare module.exports: any;
}

declare module 'electron-forge/dist/installers/win32/exe' {
  declare module.exports: any;
}

declare module 'electron-forge/dist/makers/darwin/dmg' {
  declare module.exports: any;
}

declare module 'electron-forge/dist/makers/generic/zip' {
  declare module.exports: any;
}

declare module 'electron-forge/dist/makers/linux/deb' {
  declare module.exports: any;
}

declare module 'electron-forge/dist/makers/linux/flatpak' {
  declare module.exports: any;
}

declare module 'electron-forge/dist/makers/linux/rpm' {
  declare module.exports: any;
}

declare module 'electron-forge/dist/makers/linux/snap' {
  declare module.exports: any;
}

declare module 'electron-forge/dist/makers/win32/appx' {
  declare module.exports: any;
}

declare module 'electron-forge/dist/makers/win32/squirrel' {
  declare module.exports: any;
}

declare module 'electron-forge/dist/makers/win32/wix' {
  declare module.exports: any;
}

declare module 'electron-forge/dist/publishers/electron-release-server' {
  declare module.exports: any;
}

declare module 'electron-forge/dist/publishers/github' {
  declare module.exports: any;
}

declare module 'electron-forge/dist/publishers/s3' {
  declare module.exports: any;
}

declare module 'electron-forge/dist/publishers/snapcraft' {
  declare module.exports: any;
}

declare module 'electron-forge/dist/util/author-name' {
  declare module.exports: any;
}

declare module 'electron-forge/dist/util/check-system' {
  declare module.exports: any;
}

declare module 'electron-forge/dist/util/compile-hook' {
  declare module.exports: any;
}

declare module 'electron-forge/dist/util/config-fn' {
  declare module.exports: any;
}

declare module 'electron-forge/dist/util/config' {
  declare module.exports: any;
}

declare module 'electron-forge/dist/util/confirm-if-interactive' {
  declare module.exports: any;
}

declare module 'electron-forge/dist/util/deprecate' {
  declare module.exports: any;
}

declare module 'electron-forge/dist/util/ensure-output' {
  declare module.exports: any;
}

declare module 'electron-forge/dist/util/forge-config' {
  declare module.exports: any;
}

declare module 'electron-forge/dist/util/get-electron-version' {
  declare module.exports: any;
}

declare module 'electron-forge/dist/util/github' {
  declare module.exports: any;
}

declare module 'electron-forge/dist/util/hdiutil' {
  declare module.exports: any;
}

declare module 'electron-forge/dist/util/hook' {
  declare module.exports: any;
}

declare module 'electron-forge/dist/util/install-dependencies' {
  declare module.exports: any;
}

declare module 'electron-forge/dist/util/is-installed' {
  declare module.exports: any;
}

declare module 'electron-forge/dist/util/linux-config' {
  declare module.exports: any;
}

declare module 'electron-forge/dist/util/linux-installer' {
  declare module.exports: any;
}

declare module 'electron-forge/dist/util/messages' {
  declare module.exports: any;
}

declare module 'electron-forge/dist/util/move-app' {
  declare module.exports: any;
}

declare module 'electron-forge/dist/util/ora-handler' {
  declare module.exports: any;
}

declare module 'electron-forge/dist/util/ora' {
  declare module.exports: any;
}

declare module 'electron-forge/dist/util/out-dir' {
  declare module.exports: any;
}

declare module 'electron-forge/dist/util/parse-archs' {
  declare module.exports: any;
}

declare module 'electron-forge/dist/util/publish-state' {
  declare module.exports: any;
}

declare module 'electron-forge/dist/util/read-package-json' {
  declare module.exports: any;
}

declare module 'electron-forge/dist/util/rebuild' {
  declare module.exports: any;
}

declare module 'electron-forge/dist/util/require-search' {
  declare module.exports: any;
}

declare module 'electron-forge/dist/util/resolve-dir' {
  declare module.exports: any;
}

declare module 'electron-forge/dist/util/terminate' {
  declare module.exports: any;
}

declare module 'electron-forge/dist/util/yarn-or-npm' {
  declare module.exports: any;
}

declare module 'electron-forge/gulpfile.babel' {
  declare module.exports: any;
}

declare module 'electron-forge/tabtab-install' {
  declare module.exports: any;
}

declare module 'electron-forge/tmpl/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'electron-forge/dist/api/import.js' {
  declare module.exports: $Exports<'electron-forge/dist/api/import'>;
}
declare module 'electron-forge/dist/api/index.js' {
  declare module.exports: $Exports<'electron-forge/dist/api/index'>;
}
declare module 'electron-forge/dist/api/init.js' {
  declare module.exports: $Exports<'electron-forge/dist/api/init'>;
}
declare module 'electron-forge/dist/api/install.js' {
  declare module.exports: $Exports<'electron-forge/dist/api/install'>;
}
declare module 'electron-forge/dist/api/lint.js' {
  declare module.exports: $Exports<'electron-forge/dist/api/lint'>;
}
declare module 'electron-forge/dist/api/make.js' {
  declare module.exports: $Exports<'electron-forge/dist/api/make'>;
}
declare module 'electron-forge/dist/api/package.js' {
  declare module.exports: $Exports<'electron-forge/dist/api/package'>;
}
declare module 'electron-forge/dist/api/publish.js' {
  declare module.exports: $Exports<'electron-forge/dist/api/publish'>;
}
declare module 'electron-forge/dist/api/start.js' {
  declare module.exports: $Exports<'electron-forge/dist/api/start'>;
}
declare module 'electron-forge/dist/electron-forge-import.js' {
  declare module.exports: $Exports<'electron-forge/dist/electron-forge-import'>;
}
declare module 'electron-forge/dist/electron-forge-init.js' {
  declare module.exports: $Exports<'electron-forge/dist/electron-forge-init'>;
}
declare module 'electron-forge/dist/electron-forge-install.js' {
  declare module.exports: $Exports<'electron-forge/dist/electron-forge-install'>;
}
declare module 'electron-forge/dist/electron-forge-lint.js' {
  declare module.exports: $Exports<'electron-forge/dist/electron-forge-lint'>;
}
declare module 'electron-forge/dist/electron-forge-make.js' {
  declare module.exports: $Exports<'electron-forge/dist/electron-forge-make'>;
}
declare module 'electron-forge/dist/electron-forge-package.js' {
  declare module.exports: $Exports<'electron-forge/dist/electron-forge-package'>;
}
declare module 'electron-forge/dist/electron-forge-publish.js' {
  declare module.exports: $Exports<'electron-forge/dist/electron-forge-publish'>;
}
declare module 'electron-forge/dist/electron-forge-start.js' {
  declare module.exports: $Exports<'electron-forge/dist/electron-forge-start'>;
}
declare module 'electron-forge/dist/electron-forge.js' {
  declare module.exports: $Exports<'electron-forge/dist/electron-forge'>;
}
declare module 'electron-forge/dist/forge-import.js' {
  declare module.exports: $Exports<'electron-forge/dist/forge-import'>;
}
declare module 'electron-forge/dist/forge-init.js' {
  declare module.exports: $Exports<'electron-forge/dist/forge-init'>;
}
declare module 'electron-forge/dist/forge-install.js' {
  declare module.exports: $Exports<'electron-forge/dist/forge-install'>;
}
declare module 'electron-forge/dist/forge-lint.js' {
  declare module.exports: $Exports<'electron-forge/dist/forge-lint'>;
}
declare module 'electron-forge/dist/forge-make.js' {
  declare module.exports: $Exports<'electron-forge/dist/forge-make'>;
}
declare module 'electron-forge/dist/forge-package.js' {
  declare module.exports: $Exports<'electron-forge/dist/forge-package'>;
}
declare module 'electron-forge/dist/forge-publish.js' {
  declare module.exports: $Exports<'electron-forge/dist/forge-publish'>;
}
declare module 'electron-forge/dist/forge-start.js' {
  declare module.exports: $Exports<'electron-forge/dist/forge-start'>;
}
declare module 'electron-forge/dist/forge.js' {
  declare module.exports: $Exports<'electron-forge/dist/forge'>;
}
declare module 'electron-forge/dist/init/init-custom.js' {
  declare module.exports: $Exports<'electron-forge/dist/init/init-custom'>;
}
declare module 'electron-forge/dist/init/init-directory.js' {
  declare module.exports: $Exports<'electron-forge/dist/init/init-directory'>;
}
declare module 'electron-forge/dist/init/init-git.js' {
  declare module.exports: $Exports<'electron-forge/dist/init/init-git'>;
}
declare module 'electron-forge/dist/init/init-npm.js' {
  declare module.exports: $Exports<'electron-forge/dist/init/init-npm'>;
}
declare module 'electron-forge/dist/init/init-standard-fix.js' {
  declare module.exports: $Exports<'electron-forge/dist/init/init-standard-fix'>;
}
declare module 'electron-forge/dist/init/init-starter-files.js' {
  declare module.exports: $Exports<'electron-forge/dist/init/init-starter-files'>;
}
declare module 'electron-forge/dist/installers/darwin/dmg.js' {
  declare module.exports: $Exports<'electron-forge/dist/installers/darwin/dmg'>;
}
declare module 'electron-forge/dist/installers/darwin/zip.js' {
  declare module.exports: $Exports<'electron-forge/dist/installers/darwin/zip'>;
}
declare module 'electron-forge/dist/installers/linux/deb.js' {
  declare module.exports: $Exports<'electron-forge/dist/installers/linux/deb'>;
}
declare module 'electron-forge/dist/installers/linux/rpm.js' {
  declare module.exports: $Exports<'electron-forge/dist/installers/linux/rpm'>;
}
declare module 'electron-forge/dist/installers/win32/exe.js' {
  declare module.exports: $Exports<'electron-forge/dist/installers/win32/exe'>;
}
declare module 'electron-forge/dist/makers/darwin/dmg.js' {
  declare module.exports: $Exports<'electron-forge/dist/makers/darwin/dmg'>;
}
declare module 'electron-forge/dist/makers/generic/zip.js' {
  declare module.exports: $Exports<'electron-forge/dist/makers/generic/zip'>;
}
declare module 'electron-forge/dist/makers/linux/deb.js' {
  declare module.exports: $Exports<'electron-forge/dist/makers/linux/deb'>;
}
declare module 'electron-forge/dist/makers/linux/flatpak.js' {
  declare module.exports: $Exports<'electron-forge/dist/makers/linux/flatpak'>;
}
declare module 'electron-forge/dist/makers/linux/rpm.js' {
  declare module.exports: $Exports<'electron-forge/dist/makers/linux/rpm'>;
}
declare module 'electron-forge/dist/makers/linux/snap.js' {
  declare module.exports: $Exports<'electron-forge/dist/makers/linux/snap'>;
}
declare module 'electron-forge/dist/makers/win32/appx.js' {
  declare module.exports: $Exports<'electron-forge/dist/makers/win32/appx'>;
}
declare module 'electron-forge/dist/makers/win32/squirrel.js' {
  declare module.exports: $Exports<'electron-forge/dist/makers/win32/squirrel'>;
}
declare module 'electron-forge/dist/makers/win32/wix.js' {
  declare module.exports: $Exports<'electron-forge/dist/makers/win32/wix'>;
}
declare module 'electron-forge/dist/publishers/electron-release-server.js' {
  declare module.exports: $Exports<'electron-forge/dist/publishers/electron-release-server'>;
}
declare module 'electron-forge/dist/publishers/github.js' {
  declare module.exports: $Exports<'electron-forge/dist/publishers/github'>;
}
declare module 'electron-forge/dist/publishers/s3.js' {
  declare module.exports: $Exports<'electron-forge/dist/publishers/s3'>;
}
declare module 'electron-forge/dist/publishers/snapcraft.js' {
  declare module.exports: $Exports<'electron-forge/dist/publishers/snapcraft'>;
}
declare module 'electron-forge/dist/util/author-name.js' {
  declare module.exports: $Exports<'electron-forge/dist/util/author-name'>;
}
declare module 'electron-forge/dist/util/check-system.js' {
  declare module.exports: $Exports<'electron-forge/dist/util/check-system'>;
}
declare module 'electron-forge/dist/util/compile-hook.js' {
  declare module.exports: $Exports<'electron-forge/dist/util/compile-hook'>;
}
declare module 'electron-forge/dist/util/config-fn.js' {
  declare module.exports: $Exports<'electron-forge/dist/util/config-fn'>;
}
declare module 'electron-forge/dist/util/config.js' {
  declare module.exports: $Exports<'electron-forge/dist/util/config'>;
}
declare module 'electron-forge/dist/util/confirm-if-interactive.js' {
  declare module.exports: $Exports<'electron-forge/dist/util/confirm-if-interactive'>;
}
declare module 'electron-forge/dist/util/deprecate.js' {
  declare module.exports: $Exports<'electron-forge/dist/util/deprecate'>;
}
declare module 'electron-forge/dist/util/ensure-output.js' {
  declare module.exports: $Exports<'electron-forge/dist/util/ensure-output'>;
}
declare module 'electron-forge/dist/util/forge-config.js' {
  declare module.exports: $Exports<'electron-forge/dist/util/forge-config'>;
}
declare module 'electron-forge/dist/util/get-electron-version.js' {
  declare module.exports: $Exports<'electron-forge/dist/util/get-electron-version'>;
}
declare module 'electron-forge/dist/util/github.js' {
  declare module.exports: $Exports<'electron-forge/dist/util/github'>;
}
declare module 'electron-forge/dist/util/hdiutil.js' {
  declare module.exports: $Exports<'electron-forge/dist/util/hdiutil'>;
}
declare module 'electron-forge/dist/util/hook.js' {
  declare module.exports: $Exports<'electron-forge/dist/util/hook'>;
}
declare module 'electron-forge/dist/util/install-dependencies.js' {
  declare module.exports: $Exports<'electron-forge/dist/util/install-dependencies'>;
}
declare module 'electron-forge/dist/util/is-installed.js' {
  declare module.exports: $Exports<'electron-forge/dist/util/is-installed'>;
}
declare module 'electron-forge/dist/util/linux-config.js' {
  declare module.exports: $Exports<'electron-forge/dist/util/linux-config'>;
}
declare module 'electron-forge/dist/util/linux-installer.js' {
  declare module.exports: $Exports<'electron-forge/dist/util/linux-installer'>;
}
declare module 'electron-forge/dist/util/messages.js' {
  declare module.exports: $Exports<'electron-forge/dist/util/messages'>;
}
declare module 'electron-forge/dist/util/move-app.js' {
  declare module.exports: $Exports<'electron-forge/dist/util/move-app'>;
}
declare module 'electron-forge/dist/util/ora-handler.js' {
  declare module.exports: $Exports<'electron-forge/dist/util/ora-handler'>;
}
declare module 'electron-forge/dist/util/ora.js' {
  declare module.exports: $Exports<'electron-forge/dist/util/ora'>;
}
declare module 'electron-forge/dist/util/out-dir.js' {
  declare module.exports: $Exports<'electron-forge/dist/util/out-dir'>;
}
declare module 'electron-forge/dist/util/parse-archs.js' {
  declare module.exports: $Exports<'electron-forge/dist/util/parse-archs'>;
}
declare module 'electron-forge/dist/util/publish-state.js' {
  declare module.exports: $Exports<'electron-forge/dist/util/publish-state'>;
}
declare module 'electron-forge/dist/util/read-package-json.js' {
  declare module.exports: $Exports<'electron-forge/dist/util/read-package-json'>;
}
declare module 'electron-forge/dist/util/rebuild.js' {
  declare module.exports: $Exports<'electron-forge/dist/util/rebuild'>;
}
declare module 'electron-forge/dist/util/require-search.js' {
  declare module.exports: $Exports<'electron-forge/dist/util/require-search'>;
}
declare module 'electron-forge/dist/util/resolve-dir.js' {
  declare module.exports: $Exports<'electron-forge/dist/util/resolve-dir'>;
}
declare module 'electron-forge/dist/util/terminate.js' {
  declare module.exports: $Exports<'electron-forge/dist/util/terminate'>;
}
declare module 'electron-forge/dist/util/yarn-or-npm.js' {
  declare module.exports: $Exports<'electron-forge/dist/util/yarn-or-npm'>;
}
declare module 'electron-forge/gulpfile.babel.js' {
  declare module.exports: $Exports<'electron-forge/gulpfile.babel'>;
}
declare module 'electron-forge/tabtab-install.js' {
  declare module.exports: $Exports<'electron-forge/tabtab-install'>;
}
declare module 'electron-forge/tmpl/index.js' {
  declare module.exports: $Exports<'electron-forge/tmpl/index'>;
}
