// flow-typed signature: cd4756e4132c1f09f54c90c46c979079
// flow-typed version: <<STUB>>/electron-prebuilt-compile_v3.0.2/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'electron-prebuilt-compile'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'electron-prebuilt-compile' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'electron-prebuilt-compile/lib/cli' {
  declare module.exports: any;
}

declare module 'electron-prebuilt-compile/lib/es6-init' {
  declare module.exports: any;
}

declare module 'electron-prebuilt-compile/lib/main' {
  declare module.exports: any;
}

declare module 'electron-prebuilt-compile/src/cli' {
  declare module.exports: any;
}

declare module 'electron-prebuilt-compile/src/es6-init' {
  declare module.exports: any;
}

declare module 'electron-prebuilt-compile/src/main' {
  declare module.exports: any;
}

// Filename aliases
declare module 'electron-prebuilt-compile/lib/cli.js' {
  declare module.exports: $Exports<'electron-prebuilt-compile/lib/cli'>;
}
declare module 'electron-prebuilt-compile/lib/es6-init.js' {
  declare module.exports: $Exports<'electron-prebuilt-compile/lib/es6-init'>;
}
declare module 'electron-prebuilt-compile/lib/main.js' {
  declare module.exports: $Exports<'electron-prebuilt-compile/lib/main'>;
}
declare module 'electron-prebuilt-compile/src/cli.js' {
  declare module.exports: $Exports<'electron-prebuilt-compile/src/cli'>;
}
declare module 'electron-prebuilt-compile/src/es6-init.js' {
  declare module.exports: $Exports<'electron-prebuilt-compile/src/es6-init'>;
}
declare module 'electron-prebuilt-compile/src/main.js' {
  declare module.exports: $Exports<'electron-prebuilt-compile/src/main'>;
}
