// flow-typed signature: 01441ad95ed2c23c354a960549b503a4
// flow-typed version: <<STUB>>/eslint-config-cooperka_v0.2.11/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-cooperka'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-cooperka' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-config-cooperka/react-native' {
  declare module.exports: any;
}

declare module 'eslint-config-cooperka/react' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-config-cooperka/index' {
  declare module.exports: $Exports<'eslint-config-cooperka'>;
}
declare module 'eslint-config-cooperka/index.js' {
  declare module.exports: $Exports<'eslint-config-cooperka'>;
}
declare module 'eslint-config-cooperka/react-native.js' {
  declare module.exports: $Exports<'eslint-config-cooperka/react-native'>;
}
declare module 'eslint-config-cooperka/react.js' {
  declare module.exports: $Exports<'eslint-config-cooperka/react'>;
}
